#!/bin/sh -e

. /usr/share/debconf/confmodule

db_input critical nasa-apod-background/api_key || :
db_go

db_get nasa-apod-background/api_key
if [ -z "$RET" ]; then
  echo "API key is required" >&2
  exit 1
fi
