#!/bin/sh -e

. /usr/share/debconf/confmodule

db_input medium nasa-apod-background/api_url || :
db_go

db_get nasa-apod-background/api_url
if [ -z "$RET" ]; then
  echo "API url is required" >&2
  exit 1
fi
