#!/bin/sh -e

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
  . /usr/share/debconf/confmodule
  db_purge
  rm -rf /opt/nasa-apod-background
else
  rm -rf /opt/nasa-apod-background/api.key
  rm -rf /opt/nasa-apod-background/cron.log
  rm -rf /opt/nasa-apod-background/logrotate.config
  rm -rf /opt/nasa-apod-background/nasa-apod-background.fish
  rm -rf /opt/nasa-apod-background/oldlogs
fi

