#!/bin/sh -e

. /usr/share/debconf/confmodule

mkdir -p /opt/nasa-apod-background

db_get nasa-apod-background/api_key
printf '%s' "$RET" > /opt/nasa-apod-background/api.key

/usr/bin/fish /opt/nasa-apod-background/nasa-apod-background.fish
